### ISSUE TITLE
Install didn't work correctly

### ISSUE THREAD

**Issue by JeffSokol** [craftsmancoding/query#5]
First off, this snippet looks fantastic. I hope to be able to use it on all my sites. Great work.

I installed the package from package management, tried to run it and got this error:

`[2015-05-14 15:06:09] (ERROR @ /core/cache/includes/elements/modsnippet/39.include.cache.php : 115) PHP warning: require_once(/core/components/query/vendor/autoload.php): failed to open stream: No such file or directory`

I looked for the autoload.php file and it did not exist.

Thanks for your help.

**Comment by fireproofsocks** [comment]
Looks like the composer stuff didn't get packaged.  You can install via Repoman and composer, but that's more technical.  Which version of the package did you download?

**Comment by JeffSokol** [comment]
Hey Everett,

 

Thanks for the quick reply.

 

I downloaded it today from here: http://modx.com/extras/package/query I believe it's 1.3.0

 

jeff sokol

web director



jeff@ave25.com

602.864.1233 ext. 3




 

Voted 2015 Best Graphic Design Firm - Arizona Foothills Magazine

Voted 2014 Best Boutique Advertising Agency - Arizona Foothills Magazine

Voted 2013 Best Web Design, Programming & Management Firm - Arizona Foothills Magazine

**Comment by fireproofsocks** [comment]
I repackaged this and release 1.3.1 today.

**Comment by JeffSokol** [comment]
Thanks Everett, I'm excited to try this out.
